# Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.



count = [1,2]
answer = 0
while count.last(2).inject(:+) < 4000000
  puls = count.last(2).inject(:+)
  count.push(puls)
end
count.each do |count|
  if count%2 == 0
    answer = answer + count
  end
end
puts answer

